dist: trusty
language: java
addons:
    firefox: "49.0"

before_install:
    - sudo apt-get install python3
    - sudo apt-get install nodejs

before_script:
  - "export DISPLAY=:99.0"
  - "./transcrypt/development/continuous_integration/run prepare"

script: "./transcrypt/development/continuous_integration/run set1"

